fix: Add compatibility to golang 386
ory/dockertest pull request #312
Opened 2021-10-11 21:20 UTC by donno2048

In golang 64 this code will work without any problem at all, but in golang 386 it needs to make sure the overflow is treated carefully, this is a solution that does not require any breaking/alerting.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.

P.S. I understand I'm supposed to suggest edits to the `master` branch but couldn't find a corresponding issue there

2021-10-12 06:50 UTC, aeneasr commented on docker/env.go
> +func parse64(x int64) int {
Could you provide the source of this function or if you wrote it yourself explain the reasoning behind the byte shift and using `bigint`? Thank you!

2021-10-12 08:56 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
Wrote it myself, the bit shift is simply checking for default size of `int` (on runtime) it uses `==32` just to make it a little simpler to view, it could be rewritten as
```go
	if uintptr(^uintptr(0) >> 63) {
		return int(x)
	} else {
		return int(new(big.Int).Mod(big.NewInt(x), big.NewInt(math.MaxInt32)).Int64())
	}
```
the `big.Int` is used to make sure after using `Mod` the result won't be negative if there was an overflow, as the default mod operator won't do that, while the `big.NewInt(math.MaxInt32)` is obviously there for the same reason of removing the overflowing bits.

2021-10-12 10:12 UTC, aeneasr commented on docker/env.go
> +func parse64(x int64) int {
I think this could be addressed by using `ParseInt(s, 10, 0)` in GetInt64 instead. Here's a bit more background on this: https://parsiya.net/blog/2020-04-05-the-golang-int-and-the-overlooked-bug/

2021-10-12 12:56 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
So you're saying you rather have 32 bit systems simply return `int32` when using the `GetInt64` method?
I think it would be way more intuitive if `GetInt64` will actually return `int64`...

2021-10-12 13:31 UTC, aeneasr commented on docker/env.go
> +func parse64(x int64) int {
As far as I understand, `ParseInt(s, 10, 0)` returns the appropriate int size for the arch. So on 64 it would be 64 bit, on 32 it would be 32 bit (with overflow).

What is the bug you are facing here actually? Do you get an error message or something like that?

2021-10-12 15:19 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
>As far as I understand, `ParseInt(s, 10, 0)` returns the appropriate int size for the arch. So on 64 it would be 64 bit, on 32 it would be 32 bit (with overflow).

Try running 

```go
package main
import (
	"fmt"
	"strconv"
)
func main() {
	x, _ := strconv.ParseInt("2222222222", 10, 0)
	fmt.Print(x)
}
```

If you run it on a 32-bit system it will print `2147483647`, not `2222222222` which means it won't be able to deal with `int64` correctly if you used that method. Replacing the `0` to `64` resolves the issue obviously, so if you **won't** change the `GetInt64` function at all it will perfectly work in 32-bit systems and my fix will resolve the issue for `GetInt`

> Do you get an error message or something like that?

Honestly, I haven't tried it

2021-10-13 07:27 UTC, aeneasr requested changes

2021-10-13 07:27 UTC, aeneasr commented on docker/env.go
> +func parse64(x int64) int {
Ok I see, so the goal of your PR is to change the behavior from overflowing to negative to just stay with the max value of int32 or to some mod representation?

I am not sure if this is a good idea to be honest. It’s a subtle but hard to spot breaking change and it’s also uncommon behavior because everyone understands int overflow going negative but noone expects it to do some math on it

2021-10-13 08:35 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
Not exactly, the current `GetInt` method won't work in 32-bit, my method will remove the overflowing bits if the `GetInt` function is used or return them too if the `GetInt64`

2021-10-13 08:39 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
Using `ParseInt(s, 10, 0)` will give `math.MaxInt32` instead of removing the overflow

2021-10-24 20:41 UTC, donno2048 commented on docker/env.go
> +func parse64(x int64) int {
@aeneasr please review again

2021-10-25 13:14 UTC, aeneasr requested changes
Sorry, I don't think this change makes sense for the following reasons:

- Environment variables are not used in the context of this library
- It would only fail if an env var int us used with > 32 bits on 386
- I think the proposed solution is counter intuitive. People understand overflow, but they probably don't understand why some integer is maxing out at a value.

As stated in a comment, this PR is not addressing an issue encountered, but an optional change. Thus, I don't think it meets the criteria for being merged.

2021-10-25 13:14 UTC, aeneasr commented
Closing as per my last review, if you disagree strongly, let's talk :)

2021-10-25 13:14 UTC, closed without merging