docs: add client ping to example
ory/dockertest pull request #396
Opened 2022-12-06 22:07 UTC by smbm

Updated Readme and Examples to be explicit about whether Docker is running or not by using `Client.Ping()`. 
Updated error returned if pool construction fails to refer to that specifically rather than `Could not connect to Docker` which never failed even if Docker was not running.
Updated the `dockertest_test.go` file to incorporate the same changes.

## Related Issue or Design Document

Fixes #395

## Checklist

- [X] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [X] I have read the [security policy](../security/policy).
- [X] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

I have run the tests as best I can but on an M1 Mac I am unable to run the MySQL 5.7 and Mongo 3.3.12 tests due to mismatching architectures. If I comment these tests out everything passes, I realise this is suboptimal.

I have not made any changes to dockertest itself, only to the tests, readme and examples. If the maintainers feel that more testing is needed then I can see what I can do. I only have Arm hardware to hand at the moment though.

2022-12-06 22:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/dockertest?pullRequest=396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/dockertest?pullRequest=396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/dockertest?pullRequest=396) it.</sub>

2022-12-07 09:55 UTC, alnr requested changes
Thank you for this great contribution! Would you mind checking the example markdown files for consistent indentation with tabs? I marked a couple of occasions.

Otherwise this looks good to merge 👍

2022-12-07 09:55 UTC, alnr commented on examples/BuildDockerfile.md
> +    log.Fatalf("Could not connect to Docker: %s", err)
Indentation is with spaces instead of tabs here.

2022-12-07 09:55 UTC, alnr commented on examples/Cassandra.md
> +    log.Fatalf("Could not connect to Docker: %s", err)
same here

2022-12-07 09:55 UTC, alnr commented on examples/CockroachDB.md
> +    log.Fatalf("Could not connect to Docker: %s", err)
same here

2022-12-07 16:53 UTC, smbm commented
> Thank you for this great contribution! Would you mind checking the example markdown files for consistent indentation with tabs? I marked a couple of occasions.
> 
> Otherwise this looks good to merge 👍

Thanks for the response! I have checked each of the example .md files and corrected the indenting to be consistent with the rest of that file. If you'd prefer I could fix the indenting of all lines in each file to be tabs or spaces.

2022-12-07 16:56 UTC, alnr approved these changes

2022-12-07 17:03 UTC, zepatrik approved these changes

2022-12-07 17:04 UTC, merged

2022-12-08 14:23 UTC, vinckr commented
Hello @smbm 
Congrats on merging your first PR in Ory 🎉 !
Your contribution will soon be helping secure millions of identities around the globe 🌏. 
As a small token of appreciation we send our first time contributors a gift package to welcome them to the community. 
[Please drop me an email and I will forward you the form to claim your Ory swag!](mailto:vincent@ory.sh)