feat: Add support for BuildKit when building images
ory/dockertest pull request #416
Opened 2023-03-08 03:12 UTC by tmc

This is a rebased push of https://github.com/ory/dockertest/pull/374

2023-04-03 08:56 UTC, zepatrik requested changes
I'm sorry to mess with this again, but can you rebase now that your other PR is merged? There seems to be a bug in the dependency scanner wrongly reporting runc, so that is fine.
https://github.com/sonatype-nexus-community/nancy/issues/273

2023-07-14 18:05 UTC, kczapla commented
Hi guys, whats the status here? I need this feature very much! :)

2025-01-02 09:43 UTC, aeneasr commented
buildkit support was added in another pr

2025-01-02 09:46 UTC, aeneasr commented
my bad, i was looking at the wrong diff

2025-01-02 09:55 UTC, aeneasr approved these changes

2025-01-02 10:06 UTC, merged